use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use utoipa::ToSchema;

/// This is the main data structure for an Employee as it looks in our Database.
/// We use it to send data FROM the server TO the user (Serialization).
#[derive(Debug, Serialize, Deserialize, FromRow, ToSchema)]
pub struct Employee {
    /// The unique ID generated by the database.
    pub id: i32,
    
    /// The first name. We use 'Option' because it might be empty (null) in the database.
    pub first_name: Option<String>,
    
    /// The last name. Also an 'Option' in case it's not provided.
    pub last_name: Option<String>,
    
    /// The email address. 'Option' means it's not strictly required by the database.
    pub email: Option<String>,
}

/// This is a special "input-only" structure used when someone wants to CREATE a new employee.
/// We don't need an 'id' here because the database creates that for us automatically.
#[derive(Debug, Deserialize, ToSchema)]
pub struct CreateEmployee {
    /// We want the first name to be a normal String (not Option) to make it mandatory.
    pub first_name: String,
    
    /// The last name is also mandatory for new entries.
    pub last_name: String,
    
    /// The email is required when creating a new record.
    pub email: String,
}